### ISSUE TITLE
add an example file for using the code as a function

### ISSUE THREAD

**Issue by goroda** [gorodetsky-umich/simulateTestCases#23]
Inputs: parameters, design variables, etc. 
Ouputs: whatever (e.g, aoa, cl, cd)

It should handle all the file IO in a directory specified by the user. The default should be a temporary directory (so its deleted).

**Comment by sinaendhran** [comment]
Added get_sim_data function in utils.py, which gets either the input yaml file or the overall_sim_out.yaml from a simulation and a run_flag and outputs a dictionary with AOA, cl, cd data. The run_flag ensures that a new simulation is optional.

**Comment by sinaendhran** [comment]
Added `run_case`, `run_naca0012`, and `run_30p30n` functions to give a dictionary of essential inputs and get outputs.
